version: '3'

services:
  mongo:
    container_name: mongo-container
    image: mongo:3.6
    restart: always
    volumes:
      - ./.data:/data/db:z
    ports:
      - "27018:27017"
  
  api:
    container_name: api-container
    image: node:12    
    restart: always    
    working_dir: /usr/src/app
    command: bash -c "npm ci --only=production && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./dist:/usr/src/app/dist
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo