version: '3'

services:
  mongo:
    container_name: mongo-container
    image: mongo:3.6
    restart: always
    volumes:
      - ./.data:/data/db
    ports:
      - "27018:27017"
  
  api:
    container_name: api-container
    build: .
    restart: always
    image: clean-node-api
    command: npm start
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
    ports:
      - "5050:5050"
    links:
      - mongo